---
- hosts: all
  become: yes
  roles:
    - { role: geerlingguy.pip, tags: [setup] }
    - { role: geerlingguy.docker, tags: [setup] }

  tasks:
    - name: Create .env file from template
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: /home/zholnik/redmine.env
        mode: '0600'
      tags: [deploy]

    - name: deploy redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        state: started
        restart_policy: always
        published_ports:
          - "{{ redmine_port }}:3000"
        env_file: /home/zholnik/redmine.env
      tags: [deploy]